#!/bin/sh
LOG="[$(date)]"
clear
echo "***************************************"
echo "Author: rz-modder"
echo "Youtube: RamZxx."
echo "Github: https://github.com/rz-modder/"
echo "***************************************"
echo
sleep 5
echo $LOG "updating..."
echo
apt update -y
apt upgrade -y
echo
echo $LOG "installing packages..."
echo
apt install sudo -y
sudo apt install nano -y
sudo apt install curl -y
sudo apt install wget -y
sudo apt install git -y
git config --global --unset core.autocrlf
echo
echo $LOG "installing libraries..."
echo
sudo apt install openjdk-17-jdk -y
sudo apt install openjdk-17-jre -y
echo
echo $LOG "done....!"
echo
exit 0
